### ISSUE TITLE
Product Landing Page

### ISSUE THREAD

**Issue by debrajrout** [debrajrout/Dev.HFest#18]
Create a landing page for a fictional product or service. Include a product description, pricing, and a call-to-action button.

**Comment by jagpreet409** [comment]
Hi, @debrajrout  I created the PR for this issue. Please review and approve.

https://github.com/debrajrout/Dev.HFest/pull/26

**Comment by debrajrout** [comment]
Thanks For Contributing. Please share the repo.

**Comment by jagpreet409** [comment]
Thanks @debrajrout. Will share this repo.

**Comment by debrajrout** [comment]
Go ahead and try to contribute more

**Comment by jagpreet409** [comment]
Yeah, will do that. Can you please review and approve other PR's too? You can check the PR. Thanks once again
