### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by debrajrout** [debrajrout/Dev.HFest#21]
Try to create Some small Projects in Python

**Comment by balogun14** [comment]
@debrajrout can i work on this

**Comment by debrajrout** [comment]
> @debrajrout can i work on this

Yaa sure

**Comment by debrajrout** [comment]
> @debrajrout can i work on this

Make sure to create your own folder and add something. Don't edit anything else.  


To get Hacktoberfest accepted Star the repo

**Comment by Warrior005** [comment]
where to post the project

**Comment by 5h0ov** [comment]
I would also like to work on this. Do we just put the projects in a folder and upload to the repo or do we have to put it in any specific folder in the repo

**Comment by debrajrout** [comment]
> I would also like to work on this.
> 
> Do we have to put them in a folder inside the Projects Folder?

Please share the repo, follow and give it a star.
Thanks for contributing

**Comment by debrajrout** [comment]
Issue closed...
