### ISSUE TITLE
Create A Simple Website

### ISSUE THREAD

**Issue by debrajrout** [debrajrout/Dev.HFest#3]
Try to create a simple website. Using HTML, CSS( If you want you can use JS)

**Comment by Git-Akshat01** [comment]
Hi! @debrajrout 
Please assign this issue to me

**Comment by debrajrout** [comment]
> Hi! @debrajrout Please assign this issue to me

Ok Make changes and PR ("Try to Describe your Changes In a Comment")

**Comment by Git-Akshat01** [comment]
Great. 
I will be making a PR in just some minutes.

**Comment by Git-Akshat01** [comment]
Hey @debrajrout I had added my project and had made a PR.

Hope to find some good news ASAP.

**Comment by debrajrout** [comment]
> Hey @debrajrout I had added my project and had made a PR.
> 
> Hope to find some good news ASAP.

Follow and Star the repo to Get Label
