### ISSUE TITLE
Write a blog or Article 

### ISSUE THREAD

**Issue by debrajrout** [debrajrout/Dev.HFest#4]
Write a blog posts or article

**Comment by jagpreet409** [comment]
Hi @debrajrout  I created the PR for ES6 (Javascript) functions. Kindly review and approve the same .

https://github.com/debrajrout/Dev.HFest/pull/24

**Comment by Kraizan** [comment]
Hey there!
I wrote an article some time ago on "Setting up Sublime Text for Competitive Programming". I would like to contribute that blog over here. Kindly assign this to me and let me know where to add my article.
