### ISSUE TITLE
HELP NEEDED

### ISSUE THREAD

**Issue by debrajrout** [debrajrout/Dev.HFest#59]
Create separate folders for web, C, Python, Java, and other projects that exist in this repo. 
Don't delete any folder just organize it in a good way.

In return, I will merge your all 4 PR.

**Comment by darshil25** [comment]
hey @debrajrout assign this to me i will do it

**Comment by debrajrout** [comment]
Please try to do it ASAP

**Comment by darshil25** [comment]
ok i have to create only folders right ?

**Comment by debrajrout** [comment]
> ok i have to create only folders right ?

Create folders and the existing folders in it. for example all Python projects in a Python Foder like that.

**Comment by darshil25** [comment]
okay doing

**Comment by debrajrout** [comment]
> > okay doing
> 
> Make the Folder like this
> 
> C PROJECTS
> 
> PYTHON PROJECTS
> 
> JAVA PROJECTS
> 
> TECH.BLOGS
> 
> REACT
> 
> APP DEV

it will be easy to access others

**Comment by darshil25** [comment]
you have rejected my pull request
may I know the reason ?

**Comment by debrajrout** [comment]
> hey @debrajrout you have rejected my pull request may I know the reason ?

Thanks for your contribution you can contribute in other issues or create a new issue . I WILL DEFINITELY MERGE IT
