### ISSUE TITLE
Create a Simple APP 

### ISSUE THREAD

**Issue by debrajrout** [debrajrout/Dev.HFest#9]
Create a Simple Application(Use whatever technology you want)

**Comment by jagpreet409** [comment]
Hi @debrajrout  I created the PR below. You can review and approve the same. If possible can you please add **hacktoberfest-accepted** label to this issue?

https://github.com/debrajrout/Dev.HFest/pull/25

**Comment by debrajrout** [comment]
Please share the repo, follow and give it a star in order to get Hacktoberfest accepted label
Thanks for contributing.

**Comment by debrajrout** [comment]
closed

**Comment by jagpreet409** [comment]
Done added star and shared the same. Thanks . Please accept label . Thanks for your review
